// ── WORD BANK ─────────────────────────────────────────────────────────────────
// 15 topics × 3 difficulty levels
// Each entry: { word: "UPPERCASE", hint: "clue" }

const WORD_BANK = {

  // ── ANIMALS ──────────────────────────────────────────────────────────────────
  animals: {
    easy: [
      { word: "CAT",      hint: "A common furry pet that meows" },
      { word: "DOG",      hint: "Man's best friend" },
      { word: "FISH",     hint: "It lives in water and has fins" },
      { word: "BIRD",     hint: "It has wings and can fly" },
      { word: "FROG",     hint: "It croaks and leaps on lily pads" },
      { word: "LION",     hint: "King of the jungle" },
      { word: "BEAR",     hint: "A large furry animal that hibernates" },
      { word: "DUCK",     hint: "It quacks and swims in ponds" },
      { word: "GOAT",     hint: "Farm animal known for eating anything" },
      { word: "WOLF",     hint: "Wild cousin of the dog, hunts in packs" },
    ],
    medium: [
      { word: "PENGUIN",   hint: "Flightless bird of the South Pole" },
      { word: "GIRAFFE",   hint: "Has the longest neck of any animal" },
      { word: "DOLPHIN",   hint: "Highly intelligent marine mammal" },
      { word: "CHEETAH",   hint: "Fastest land animal on Earth" },
      { word: "GORILLA",   hint: "Largest living primate" },
      { word: "PANTHER",   hint: "Big black cat of the wild" },
      { word: "HAMSTER",   hint: "Small rodent popular as a pet" },
      { word: "LOBSTER",   hint: "A crustacean with large claws" },
      { word: "PEACOCK",   hint: "Bird famous for its colourful tail fan" },
      { word: "FLAMINGO",  hint: "Pink bird that stands on one leg" },
    ],
    hard: [
      { word: "PLATYPUS",     hint: "Egg-laying mammal with a duck bill" },
      { word: "NARWHAL",      hint: "Arctic whale with a long spiral tusk" },
      { word: "AXOLOTL",      hint: "Mexican salamander that regenerates limbs" },
      { word: "CAPYBARA",     hint: "World's largest rodent from South America" },
      { word: "WOLVERINE",    hint: "Fierce, bear-like weasel of the forest" },
      { word: "PANGOLIN",     hint: "Scaly mammal often called a pinecone animal" },
      { word: "TAPIR",        hint: "Tropical mammal with a prehensile snout" },
      { word: "QUOKKA",       hint: "Smiling marsupial native to Australia" },
      { word: "BINTURONG",    hint: "Bearcat that smells like popcorn" },
      { word: "OCELOT",       hint: "Small spotted wild cat of the Americas" },
    ],
  },

  // ── VEGETABLES ───────────────────────────────────────────────────────────────
  vegetables: {
    easy: [
      { word: "CARROT",  hint: "Orange veggie rabbits love" },
      { word: "ONION",   hint: "It makes you cry when you cut it" },
      { word: "POTATO",  hint: "Used to make chips and fries" },
      { word: "TOMATO",  hint: "Red fruit often mistaken for a vegetable" },
      { word: "CORN",    hint: "Yellow grains on a long cob" },
      { word: "BEAN",    hint: "Small legume grown in pods" },
      { word: "PEA",     hint: "Tiny round green vegetable" },
      { word: "GARLIC",  hint: "Keeps vampires away, flavours food" },
      { word: "RADISH",  hint: "Small red root vegetable with a peppery taste" },
      { word: "CABBAGE", hint: "Round leafy head of a vegetable" },
    ],
    medium: [
      { word: "BROCCOLI",   hint: "Green tree-shaped vegetable" },
      { word: "SPINACH",    hint: "Popeye's favourite leafy green" },
      { word: "ZUCCHINI",   hint: "Long green summer squash" },
      { word: "EGGPLANT",   hint: "Purple vegetable also called aubergine" },
      { word: "ASPARAGUS",  hint: "Tall green spears served as a side dish" },
      { word: "ARTICHOKE",  hint: "Thistle-like vegetable with edible heart" },
      { word: "BEETROOT",   hint: "Deep red root that stains everything" },
      { word: "LEEK",       hint: "Long white onion-like vegetable" },
      { word: "PARSNIP",    hint: "Pale, sweet relative of the carrot" },
      { word: "CELERY",     hint: "Crunchy stalk vegetable with strings" },
    ],
    hard: [
      { word: "KOHLRABI",    hint: "Alien-looking bulb vegetable in the cabbage family" },
      { word: "CELERIAC",    hint: "Knobbly root related to celery" },
      { word: "ROMANESCO",   hint: "Fractal-shaped green vegetable" },
      { word: "JICAMA",      hint: "Crunchy Mexican turnip eaten raw" },
      { word: "RUTABAGA",    hint: "Yellow-fleshed root vegetable, a cabbage-turnip cross" },
      { word: "FIDDLEHEAD",  hint: "Coiled young fern frond eaten as a vegetable" },
      { word: "SUNCHOKE",    hint: "Bumpy tuber also called Jerusalem artichoke" },
      { word: "RADICCHIO",   hint: "Bitter red Italian chicory" },
      { word: "BOK CHOY",    hint: "Chinese white-stemmed cabbage" },
      { word: "TARO",        hint: "Starchy tropical root with purple flesh" },
    ],
  },

  // ── OBJECTS ──────────────────────────────────────────────────────────────────
  objects: {
    easy: [
      { word: "CHAIR",   hint: "You sit on it" },
      { word: "TABLE",   hint: "Flat surface you eat on" },
      { word: "CLOCK",   hint: "Tells you the time" },
      { word: "PHONE",   hint: "You call people with this" },
      { word: "SPOON",   hint: "Used to scoop soup" },
      { word: "LAMP",    hint: "Gives light in a room" },
      { word: "BOOK",    hint: "Has pages and a story inside" },
      { word: "FORK",    hint: "Four-pronged eating utensil" },
      { word: "MIRROR",  hint: "Shows your reflection" },
      { word: "PILLOW",  hint: "You rest your head on this in bed" },
    ],
    medium: [
      { word: "SCISSORS",   hint: "Two blades joined together for cutting" },
      { word: "COMPASS",    hint: "Points north; used for navigation" },
      { word: "THERMOS",    hint: "Insulated flask that keeps drinks hot or cold" },
      { word: "STAPLER",    hint: "Binds papers together with metal pins" },
      { word: "LANTERN",    hint: "Portable case holding a light source" },
      { word: "CALENDAR",   hint: "Shows all the days and months of a year" },
      { word: "UMBRELLA",   hint: "Keeps you dry in the rain" },
      { word: "SUITCASE",   hint: "Luggage you take on trips" },
      { word: "TELESCOPE",  hint: "Makes distant stars look closer" },
      { word: "HOURGLASS",  hint: "Measures time with falling sand" },
    ],
    hard: [
      { word: "PERISCOPE",    hint: "Tube with mirrors used in submarines to see above water" },
      { word: "ABACUS",       hint: "Ancient counting tool with sliding beads" },
      { word: "ASTROLABE",    hint: "Historical instrument used to measure star positions" },
      { word: "SEXTANT",      hint: "Navigation tool for measuring angular distance" },
      { word: "CALLIPERS",    hint: "Device that precisely measures thickness or diameter" },
      { word: "METRONOME",    hint: "Musical device that ticks at a set tempo" },
      { word: "GYROSCOPE",    hint: "Spinning wheel that resists change in orientation" },
      { word: "PROTRACTOR",   hint: "Semicircular tool for measuring angles" },
      { word: "BELLOWS",      hint: "Device that pumps air into a fire" },
      { word: "PANTOGRAPH",   hint: "Mechanical linkage used to copy and scale drawings" },
    ],
  },

  // ── VERBS ────────────────────────────────────────────────────────────────────
  verbs: {
    easy: [
      { word: "RUN",    hint: "Move quickly on foot" },
      { word: "EAT",    hint: "Consume food" },
      { word: "JUMP",   hint: "Leap off the ground" },
      { word: "SLEEP",  hint: "Rest with eyes closed" },
      { word: "SING",   hint: "Make music with your voice" },
      { word: "DANCE",  hint: "Move rhythmically to music" },
      { word: "THROW",  hint: "Launch something through the air" },
      { word: "CLIMB",  hint: "Go up using hands and feet" },
      { word: "SMILE",  hint: "Show happiness with your face" },
      { word: "WRITE",  hint: "Put words on paper" },
    ],
    medium: [
      { word: "WHISPER",   hint: "Speak very softly" },
      { word: "SCATTER",   hint: "Throw in many directions" },
      { word: "STUMBLE",   hint: "Trip and nearly fall" },
      { word: "SHATTER",   hint: "Break into many pieces" },
      { word: "WANDER",    hint: "Walk without a destination" },
      { word: "DEVOUR",    hint: "Eat hungrily and quickly" },
      { word: "HARVEST",   hint: "Gather crops from the field" },
      { word: "PERSUADE",  hint: "Convince someone to do something" },
      { word: "OBSERVE",   hint: "Watch carefully" },
      { word: "COLLAPSE",  hint: "Fall down suddenly" },
    ],
    hard: [
      { word: "PROCRASTINATE",  hint: "Delay doing something you should do now" },
      { word: "EXACERBATE",     hint: "Make a problem worse" },
      { word: "DELIBERATE",     hint: "Think carefully before deciding" },
      { word: "CIRCUMNAVIGATE", hint: "Travel completely around something" },
      { word: "EXTRAPOLATE",    hint: "Extend known data beyond its range to make predictions" },
      { word: "ASSIMILATE",     hint: "Absorb and integrate information or people" },
      { word: "OSCILLATE",      hint: "Swing back and forth repeatedly" },
      { word: "CORROBORATE",    hint: "Confirm or support a statement with evidence" },
      { word: "REVERBERATE",    hint: "Echo and continue as sound waves bounce around" },
      { word: "EXONERATE",      hint: "Officially clear someone of blame" },
    ],
  },

  // ── CELEBRITIES ──────────────────────────────────────────────────────────────
  celebrities: {
    easy: [
      { word: "BEYONCE",   hint: "Queen Bey, pop superstar" },
      { word: "DRAKE",     hint: "Canadian rapper and 'God's Plan' artist" },
      { word: "ADELE",     hint: "British singer famous for 'Hello'" },
      { word: "EMINEM",    hint: "Rap god from Detroit" },
      { word: "RIHANNA",   hint: "Barbadian pop star turned beauty mogul" },
      { word: "SHAKIRA",   hint: "Colombian singer whose hips don't lie" },
      { word: "TYGA",      hint: "Rapper famous for 'Taste'" },
      { word: "SHREK",     hint: "Fictional ogre — and internet icon" },
      { word: "KANYE",     hint: "Polarising rapper and fashion designer" },
      { word: "MADONNA",   hint: "Pop icon known as the Material Girl" },
    ],
    medium: [
      { word: "BILLIE EILISH",  hint: "Green-haired singer of 'Bad Guy'" },
      { word: "ELON MUSK",      hint: "Billionaire behind Tesla and SpaceX" },
      { word: "LADY GAGA",      hint: "Born This Way pop sensation" },
      { word: "POST MALONE",    hint: "Tattooed rapper with face tattoos" },
      { word: "TAYLOR SWIFT",   hint: "Singer known for 'Shake It Off' and 'Eras Tour'" },
      { word: "DOJA CAT",       hint: "Rapper-singer behind 'Say So'" },
      { word: "CHRIS ROCK",     hint: "Comedian slapped at the Oscars" },
      { word: "KIM KARDASHIAN", hint: "Reality TV star turned shapewear mogul" },
      { word: "RYAN REYNOLDS",  hint: "Deadpool actor and gin entrepreneur" },
      { word: "JEFF BEZOS",     hint: "Amazon founder and space tourist" },
    ],
    hard: [
      { word: "ZENDAYA",          hint: "Actress and singer, star of Euphoria" },
      { word: "DWAYNE JOHNSON",   hint: "The Rock — wrestler turned Hollywood star" },
      { word: "CARDI B",          hint: "Rapper famous for 'WAP'" },
      { word: "TIMOTHEE CHALAMET",hint: "French-American actor in Dune and Wonka" },
      { word: "MARGOT ROBBIE",    hint: "Australian actress who played Barbie" },
      { word: "PEWDIEPIE",        hint: "Swedish YouTuber, once most subscribed" },
      { word: "MARK ZUCKERBERG",  hint: "Facebook / Meta founder and CEO" },
      { word: "ALEXANDR VOLKANOVSKI", hint: "Australian UFC featherweight champion" },
      { word: "SABRINA CARPENTER",hint: "Pop star behind 'Espresso'" },
      { word: "CHARLI XCXPUSH",   hint: "Pop star known for brat summer" },
    ],
  },

  // ── MEMES ────────────────────────────────────────────────────────────────────
  memes: {
    easy: [
      { word: "DOGE",        hint: "Much wow. Such Shiba Inu." },
      { word: "YOLO",        hint: "You Only Live Once" },
      { word: "RICK ROLL",   hint: "Never gonna give you up, never gonna let you down" },
      { word: "KAREN",       hint: "Can I speak to the manager?" },
      { word: "GIGACHAD",    hint: "Extremely confident and dominant guy meme" },
      { word: "BASED",       hint: "Internet slang for confident and unapologetic" },
      { word: "SIMP",        hint: "Someone who does too much for a crush" },
      { word: "MALD",        hint: "Mad + bald; Twitch slang for rage" },
      { word: "RATIO",       hint: "When replies > likes on a tweet; a loss" },
      { word: "BOOMER",      hint: "OK ___. Used on someone behind the times" },
    ],
    medium: [
      { word: "UGANDAN KNUCKLES",  hint: "Do you know de wey? VRChat meme" },
      { word: "DISTRACTED BOYFRIEND", hint: "Stock photo guy looking at another woman" },
      { word: "SURPRISED PIKACHU", hint: "The yellow Pokemon looking shocked" },
      { word: "PEPE THE FROG",     hint: "Green frog with many moods" },
      { word: "HARAMBE",           hint: "Dicks out for this gorilla, RIP 2016" },
      { word: "TROLLFACE",         hint: "Problem? The original troll" },
      { word: "CHAD",              hint: "The ultimate alpha male silhouette meme" },
      { word: "SHRUG GUY",         hint: "¯\\_(ツ)_/¯ the emoticon person" },
      { word: "DARK HUMOR",        hint: "Comedy that makes you laugh and feel bad" },
      { word: "NYAN CAT",          hint: "Rainbow-pooping pop-tart cat flying in space" },
    ],
    hard: [
      { word: "LOSS",               hint: "A stick figure webcomic that spawned a thousand edits" },
      { word: "SHREK IS LOVE",      hint: "A horror-fairy-tale meme about devotion to an ogre" },
      { word: "STONKS",             hint: "Meme man on a rising graph for bad financial decisions" },
      { word: "GALAXY BRAIN",       hint: "Taking many leaps of logic to reach an absurd conclusion" },
      { word: "THAT'S THE JOKE",    hint: "Arrested Development Michael Bluth explaining humour" },
      { word: "BONE HURTING JUICE", hint: "Absurdist meme where drinking causes bone pain" },
      { word: "WOJAK",              hint: "Sad MS Paint face that spawned many variants" },
      { word: "SANIC",              hint: "Poorly drawn Sonic the Hedgehog meme" },
      { word: "PLANKING",           hint: "2011 trend of lying face-down in strange places" },
      { word: "ICE BUCKET CHALLENGE", hint: "Viral 2014 ALS charity challenge involving cold water" },
    ],
  },

  // ── CHARACTERS ───────────────────────────────────────────────────────────────
  characters: {
    easy: [
      { word: "MARIO",       hint: "Nintendo's red-hatted plumber" },
      { word: "BATMAN",      hint: "Dark Knight of Gotham City" },
      { word: "PIKACHU",     hint: "Yellow electric mouse Pokémon" },
      { word: "ELSA",        hint: "Frozen queen who lets it go" },
      { word: "SIMBA",       hint: "Lion King cub who becomes king" },
      { word: "SHREK",       hint: "Lovable green ogre of the swamp" },
      { word: "SPONGEBOB",   hint: "Square yellow sea sponge who fries burgers" },
      { word: "NARUTO",      hint: "Ninja who wants to be Hokage" },
      { word: "GOKU",        hint: "Saiyan warrior who loves fighting strong enemies" },
      { word: "SONIC",       hint: "Blue hedgehog who runs really fast" },
    ],
    medium: [
      { word: "GANDALF",        hint: "Grey wizard of Middle-earth" },
      { word: "HERMIONE",       hint: "Brightest witch of her age at Hogwarts" },
      { word: "WALTER WHITE",   hint: "Chemistry teacher turned drug kingpin" },
      { word: "DARTH VADER",    hint: "I am your father — Star Wars villain" },
      { word: "IRON MAN",       hint: "Tony Stark in a metal suit" },
      { word: "LEVI ACKERMAN",  hint: "Humanity's strongest soldier in AoT" },
      { word: "ITACHI UCHIHA",  hint: "Tragic Naruto villain who sacrificed everything" },
      { word: "LIGHT YAGAMI",   hint: "Death Note protagonist who becomes a god" },
      { word: "GOJO SATORU",    hint: "Infinity-wielding sorcerer from JJK" },
      { word: "EREN YEAGER",    hint: "Attack on Titan protagonist who rumbles the world" },
    ],
    hard: [
      { word: "TYRION LANNISTER",   hint: "The Imp, witty dwarf of Game of Thrones" },
      { word: "NIER AUTOMATA",      hint: "Android warrior 2B's game title" },
      { word: "GYUTARO",            hint: "Upper Moon 6 demon from Demon Slayer" },
      { word: "SUKUNA",             hint: "King of Curses with many mouths in JJK" },
      { word: "FULLMETAL ALCHEMIST",hint: "Edward Elric's title in the anime" },
      { word: "MERUEM",             hint: "Ant King from Hunter x Hunter" },
      { word: "ESCANOR",            hint: "The One — Lion's Sin of Pride in Seven Deadly Sins" },
      { word: "GRIFFITH",           hint: "Berserk villain who sacrificed his comrades" },
      { word: "SQUEALER",           hint: "Scheming boar in Sword Art Online: ALO arc" },
      { word: "YOSHIKAGE KIRA",     hint: "JoJo villain who just wants a quiet life" },
    ],
  },

  // ── INSECTS ──────────────────────────────────────────────────────────────────
  insects: {
    easy: [
      { word: "ANT",         hint: "Tiny insect that carries 50x its weight" },
      { word: "BEE",         hint: "Makes honey and pollinates flowers" },
      { word: "FLY",         hint: "Annoying insect attracted to food" },
      { word: "MOTH",        hint: "Night butterfly drawn to light" },
      { word: "WASP",        hint: "Yellow and black stinging insect" },
      { word: "FLEA",        hint: "Tiny jumping parasite on pets" },
      { word: "LICE",        hint: "Parasites that live in hair" },
      { word: "TICK",        hint: "Blood-sucking arachnid that burrows in skin" },
      { word: "GNAT",        hint: "Tiny flying insect that swarms near fruit" },
      { word: "CRICKET",     hint: "Chirping insect of the night" },
    ],
    medium: [
      { word: "DRAGONFLY",   hint: "Iridescent winged insect that hovers over water" },
      { word: "FIREFLY",     hint: "Glowing insect of summer nights" },
      { word: "CENTIPEDE",   hint: "Many-legged creepy crawly" },
      { word: "PRAYING MANTIS", hint: "Insect that looks like it's praying" },
      { word: "LADYBIRD",    hint: "Red spotted beetle considered lucky" },
      { word: "TERMITE",     hint: "Insect that eats through wood" },
      { word: "HORNET",      hint: "Large and aggressive cousin of the wasp" },
      { word: "SILVERFISH",  hint: "Fast shiny insect found in bathrooms" },
      { word: "EARWIG",      hint: "Insect with a pincer at its tail" },
      { word: "LOCUST",      hint: "Swarming insect that devastates crops" },
    ],
    hard: [
      { word: "BOMBARDIER BEETLE",  hint: "Insect that shoots boiling chemicals from its abdomen" },
      { word: "WALKINGSTICK",       hint: "Camouflaged insect that looks like a twig" },
      { word: "ASSASSIN BUG",       hint: "Predatory insect that stabs prey with a rostrum" },
      { word: "VELVET ANT",         hint: "Hairy wasp whose sting is called a cow killer" },
      { word: "ATLAS MOTH",         hint: "One of the world's largest moths" },
      { word: "GOLIATH BEETLE",     hint: "Heaviest insect on Earth" },
      { word: "TARANTULA HAWK",     hint: "Wasp that paralyses tarantulas for its larvae" },
      { word: "DOBSONFLY",          hint: "Large insect with impressive mandibles" },
      { word: "THORN BUG",          hint: "Treehoppper that disguises itself as a plant thorn" },
      { word: "GLOWWORM",           hint: "Larvae that emits bioluminescent light in caves" },
    ],
  },

  // ── FOODS ────────────────────────────────────────────────────────────────────
  foods: {
    easy: [
      { word: "PIZZA",     hint: "Italian flatbread with toppings" },
      { word: "BURGER",    hint: "Meat patty in a bun" },
      { word: "SUSHI",     hint: "Japanese rice rolls with fish" },
      { word: "PASTA",     hint: "Italian noodle dish" },
      { word: "CAKE",      hint: "Sweet baked treat for birthdays" },
      { word: "CHIPS",     hint: "Fried or baked thin potato slices" },
      { word: "TACO",      hint: "Mexican folded tortilla with fillings" },
      { word: "SOUP",      hint: "Liquid hot food eaten with a spoon" },
      { word: "OMELETTE",  hint: "Eggs beaten and fried in a pan" },
      { word: "PANCAKE",   hint: "Flat cake cooked on a griddle" },
    ],
    medium: [
      { word: "RAMEN",        hint: "Japanese noodle soup with broth and toppings" },
      { word: "BURRITO",      hint: "Flour tortilla wrapped around rice and beans" },
      { word: "LASAGNE",      hint: "Layered Italian pasta bake" },
      { word: "CROISSANT",    hint: "Buttery flaky French pastry" },
      { word: "POUTINE",      hint: "Canadian fries topped with gravy and cheese curds" },
      { word: "BIRYANI",      hint: "South Asian spiced rice dish" },
      { word: "PAELLA",       hint: "Spanish saffron rice with seafood" },
      { word: "BAKLAVA",      hint: "Middle Eastern sweet pastry with nuts and honey" },
      { word: "DUMPLINGS",    hint: "Dough pockets stuffed with meat or vegetables" },
      { word: "SHAKSHUKA",    hint: "Eggs poached in spiced tomato sauce" },
    ],
    hard: [
      { word: "BOEUF BOURGUIGNON",  hint: "Classic French beef braised in red wine" },
      { word: "MOLE POBLANO",       hint: "Mexican sauce with chocolate and over 20 spices" },
      { word: "PEKING DUCK",        hint: "Crispy-skinned Chinese roasted duck dish" },
      { word: "CEVICHE",            hint: "Latin American raw fish cured in citrus juice" },
      { word: "GOULASH",            hint: "Hungarian paprika-spiced beef stew" },
      { word: "KHACHAPURI",         hint: "Georgian cheese-filled bread boat with an egg" },
      { word: "RENDANG",            hint: "Indonesian slow-cooked dry beef curry" },
      { word: "BIBIMBAP",           hint: "Korean rice bowl mixed with veggies and gochujang" },
      { word: "DOLMADES",           hint: "Greek stuffed vine leaves" },
      { word: "INJERA",             hint: "Ethiopian spongy sourdough flatbread" },
    ],
  },

  // ── SPORTS ───────────────────────────────────────────────────────────────────
  sports: {
    easy: [
      { word: "FOOTBALL",   hint: "Most popular sport on Earth" },
      { word: "TENNIS",     hint: "Played with a racket and yellow ball" },
      { word: "SWIMMING",   hint: "Racing through water using strokes" },
      { word: "BOXING",     hint: "Fighting sport with padded gloves" },
      { word: "CYCLING",    hint: "Racing on two wheels" },
      { word: "CRICKET",    hint: "Bat-and-ball sport popular in India and England" },
      { word: "GOLF",       hint: "Get the ball in the hole in fewest shots" },
      { word: "RUGBY",      hint: "Like football but you can carry the ball" },
      { word: "HOCKEY",     hint: "Played on ice or grass with a stick and puck" },
      { word: "VOLLEYBALL", hint: "Keep the ball from touching the ground on your side" },
    ],
    medium: [
      { word: "BADMINTON",    hint: "Racket sport played with a shuttlecock" },
      { word: "WRESTLING",    hint: "Combat sport of grappling and pins" },
      { word: "TRIATHLON",    hint: "Swim, cycle, and run in one race" },
      { word: "SKATEBOARDING",hint: "Tricks on a wooden board with four wheels" },
      { word: "SQUASH",       hint: "Racket sport played in an enclosed court" },
      { word: "ARCHERY",      hint: "Shooting arrows at a target" },
      { word: "FENCING",      hint: "Sword-fighting sport in white suits" },
      { word: "POLO",         hint: "Hockey on horseback" },
      { word: "LACROSSE",     hint: "Stick sport with a netted pocket" },
      { word: "TAEKWONDO",    hint: "Korean martial art known for high kicks" },
    ],
    hard: [
      { word: "SEPAKTAKRAW",    hint: "Southeast Asian rattan ball sport using feet" },
      { word: "HURLING",        hint: "Fast Irish sport with a wooden stick called a hurley" },
      { word: "KABADDI",        hint: "South Asian contact sport with tag and breath-holding" },
      { word: "LUGE",           hint: "Sled sport lying face-up on a frozen track" },
      { word: "BIATHLON",       hint: "Cross-country skiing combined with rifle shooting" },
      { word: "KORFBALL",       hint: "Mixed-gender sport similar to basketball from the Netherlands" },
      { word: "PELOTA",         hint: "Basque ball sport played against a wall" },
      { word: "SUMO",           hint: "Japanese wrestling where you push the opponent out of the ring" },
      { word: "SKELETON",       hint: "Head-first solo sled sport on a luge track" },
      { word: "CAMOGIE",        hint: "Irish hurling variant played by women" },
    ],
  },

  // ── MYTHOLOGY ────────────────────────────────────────────────────────────────
  mythology: {
    easy: [
      { word: "ZEUS",      hint: "King of the Greek gods, lord of lightning" },
      { word: "THOR",      hint: "Norse god of thunder with a hammer" },
      { word: "MEDUSA",    hint: "Snake-haired monster whose gaze turns you to stone" },
      { word: "HADES",     hint: "Greek god of the underworld" },
      { word: "APOLLO",    hint: "Greek god of the sun and music" },
      { word: "TITAN",     hint: "Race of giant deities that preceded the Greek gods" },
      { word: "SPHINX",    hint: "Lion with a human head that asks riddles" },
      { word: "PEGASUS",   hint: "White winged horse of Greek myth" },
      { word: "HERCULES",  hint: "Strongest hero in Greek mythology" },
      { word: "CYCLOPS",   hint: "One-eyed giant of Greek myth" },
    ],
    medium: [
      { word: "POSEIDON",    hint: "Greek god of the sea and earthquakes" },
      { word: "ATHENA",      hint: "Greek goddess of wisdom and war strategy" },
      { word: "LOKI",        hint: "Trickster god of Norse mythology" },
      { word: "ANUBIS",      hint: "Egyptian god with a jackal's head, guardian of the dead" },
      { word: "MINOTAUR",    hint: "Half-man half-bull trapped in the Labyrinth" },
      { word: "ODYSSEUS",    hint: "Greek hero of the epic Odyssey" },
      { word: "PERSEPHONE",  hint: "Queen of the Underworld, daughter of Demeter" },
      { word: "FENRIR",      hint: "Monstrous wolf of Norse mythology, son of Loki" },
      { word: "CHIMERA",     hint: "Fire-breathing creature with lion, goat, and serpent parts" },
      { word: "VALKYRIE",    hint: "Norse female figures who choose which warriors die" },
    ],
    hard: [
      { word: "QUETZALCOATL",    hint: "Feathered serpent god of the Aztecs" },
      { word: "GILGAMESH",       hint: "Hero-king from the oldest recorded epic in human history" },
      { word: "IZANAMI",         hint: "Japanese goddess of creation and death" },
      { word: "APOPHIS",         hint: "Ancient Egyptian serpent of chaos and darkness" },
      { word: "TEZCATLIPOCA",    hint: "Aztec god of the night sky and sorcery" },
      { word: "TIAMAT",          hint: "Babylonian dragon goddess of primordial chaos" },
      { word: "ERESHKIGAL",      hint: "Sumerian queen of the Great Below" },
      { word: "MORRIGAN",        hint: "Irish goddess of fate and war who appears as a crow" },
      { word: "ANANSI",          hint: "West African spider trickster god of stories" },
      { word: "COYOLXAUHQUI",    hint: "Aztec moon goddess decapitated by Huitzilopochtli" },
    ],
  },

  // ── BODY PARTS ───────────────────────────────────────────────────────────────
  "body parts": {
    easy: [
      { word: "EAR",      hint: "You hear with these" },
      { word: "NOSE",     hint: "You smell and breathe through this" },
      { word: "KNEE",     hint: "The joint in the middle of your leg" },
      { word: "CHIN",     hint: "The bottom of your face" },
      { word: "ANKLE",    hint: "Joint connecting foot to leg" },
      { word: "THUMB",    hint: "The widest finger on your hand" },
      { word: "ELBOW",    hint: "The bendy joint in your arm" },
      { word: "SPINE",    hint: "Column of bones down your back" },
      { word: "SKULL",    hint: "The bony case protecting your brain" },
      { word: "TONGUE",   hint: "Muscle in your mouth used to taste and speak" },
    ],
    medium: [
      { word: "CLAVICLE",   hint: "The collarbone" },
      { word: "STERNUM",    hint: "The breastbone in the centre of your chest" },
      { word: "FEMUR",      hint: "The longest bone in the human body" },
      { word: "TIBIA",      hint: "The shin bone" },
      { word: "EARDRUM",    hint: "Thin membrane that vibrates with sound" },
      { word: "CORNEA",     hint: "Transparent front layer of the eye" },
      { word: "TRACHEA",    hint: "The windpipe carrying air to the lungs" },
      { word: "PANCREAS",   hint: "Organ that produces insulin" },
      { word: "DELTOID",    hint: "Triangular shoulder muscle" },
      { word: "PHILTRUM",   hint: "The vertical groove between nose and upper lip" },
    ],
    hard: [
      { word: "HIPPOCAMPUS",   hint: "Brain region critical for forming memories" },
      { word: "AMYGDALA",      hint: "Almond-shaped brain region for processing emotions" },
      { word: "METATARSAL",    hint: "Bones in the middle of the foot" },
      { word: "PHALANGES",     hint: "Finger and toe bones" },
      { word: "PERISTALSIS",   hint: "Wave-like muscle movement that moves food down the gut" },
      { word: "CEREBELLUM",    hint: "Brain structure at the back controlling balance" },
      { word: "HYPOTHALAMUS",  hint: "Brain region regulating hunger, thirst and temperature" },
      { word: "MENISCUS",      hint: "Cartilage disc acting as a cushion in the knee joint" },
      { word: "SARTORIUS",     hint: "Longest muscle in the human body, crossing the thigh" },
      { word: "GLOTTIS",       hint: "The opening between the vocal cords in the larynx" },
    ],
  },

  // ── BRAIN ROT ─────────────────────────────────────────────────────────────────
  "brain rot": {
    easy: [
      { word: "RIZZ",         hint: "Charisma or ability to attract others; Gen Z slang" },
      { word: "NPC",          hint: "Non-player character; someone acting robotically" },
      { word: "SLAY",         hint: "To do something impressively well" },
      { word: "BUSSIN",       hint: "Really good, especially about food" },
      { word: "CAP",          hint: "A lie or exaggeration; 'no cap' means for real" },
      { word: "SUS",          hint: "Suspicious — from Among Us" },
      { word: "VIBE",         hint: "The feeling or atmosphere of a place or person" },
      { word: "HIT DIFFERENT",hint: "To feel more impactful in a certain context" },
      { word: "RENT FREE",    hint: "Living in your head without permission" },
      { word: "ATE",          hint: "Did something exceptionally well, left no crumbs" },
    ],
    medium: [
      { word: "SIGMA MALE",      hint: "Lone wolf archetype that does not care about hierarchy" },
      { word: "SKIBIDI TOILET",  hint: "YouTube animated series with heads in toilets" },
      { word: "DELULU",          hint: "Delusional, usually about a celebrity crush" },
      { word: "UNDERSTOOD THE ASSIGNMENT", hint: "Someone performed exactly as expected or better" },
      { word: "MAIN CHARACTER",  hint: "Believing you're the protagonist of real life" },
      { word: "NO CAP",          hint: "Absolutely true, not lying at all" },
      { word: "GLAZING",         hint: "Excessive praise or flattery of someone" },
      { word: "CHRONICALLY ONLINE", hint: "Someone who spends too much time on the internet" },
      { word: "GIRL DINNER",     hint: "A random snack assortment as a meal" },
      { word: "BRAT",            hint: "Charli XCX aesthetic: confident, messy, unbothered" },
    ],
    hard: [
      { word: "GYATT",              hint: "An exclamation of admiration for a large posterior" },
      { word: "FANUM TAX",          hint: "When a streamer takes food off another's plate" },
      { word: "GRIMACE SHAKE",      hint: "McDonalds purple drink that went viral as a death meme" },
      { word: "RIZZ GOD",           hint: "Someone with absolutely unparalleled charisma" },
      { word: "MOTHER I SOBER",     hint: "Kendrick Lamar lyric turned ironic meme" },
      { word: "OHIO MEME",          hint: "State turned synonym for bizarre or cursed events" },
      { word: "PRAYING THEY EAT",   hint: "Hoping someone faces consequences for their actions" },
      { word: "VILLAIN ERA",        hint: "Choosing to prioritise yourself with zero apology" },
      { word: "REAL AND TRUE",      hint: "Affirming something with exaggerated sincerity online" },
      { word: "CAUGHT IN FOUR K",   hint: "Having your bad behaviour recorded or exposed clearly" },
    ],
  },

  // ── COUNTRIES ────────────────────────────────────────────────────────────────
  countries: {
    easy: [
      { word: "INDIA",      hint: "Home of the Taj Mahal and cricket" },
      { word: "CHINA",      hint: "Most populous country in the world" },
      { word: "JAPAN",      hint: "Land of the rising sun" },
      { word: "FRANCE",     hint: "Country famous for the Eiffel Tower" },
      { word: "BRAZIL",     hint: "Largest country in South America" },
      { word: "CANADA",     hint: "Country with a maple leaf on its flag" },
      { word: "EGYPT",      hint: "Land of pyramids and the Nile" },
      { word: "ITALY",      hint: "Shaped like a boot, home of pasta and pizza" },
      { word: "SPAIN",      hint: "Country of flamenco and bullfighting" },
      { word: "RUSSIA",     hint: "Largest country in the world by area" },
    ],
    medium: [
      { word: "ARGENTINA",    hint: "South American nation, home of Messi and tango" },
      { word: "ETHIOPIA",     hint: "African country known as the birthplace of coffee" },
      { word: "UKRAINE",      hint: "Eastern European nation whose flag is blue and yellow" },
      { word: "INDONESIA",    hint: "Archipelago of over 17,000 islands in Southeast Asia" },
      { word: "SINGAPORE",    hint: "Tiny city-state in Southeast Asia known for cleanliness" },
      { word: "COLOMBIA",     hint: "South American country known for coffee and emeralds" },
      { word: "PORTUGAL",     hint: "Country that once sailed to discover the world" },
      { word: "PAKISTAN",     hint: "South Asian country with the K2 mountain" },
      { word: "NIGERIA",      hint: "Most populous country in Africa" },
      { word: "VIETNAM",      hint: "Southeast Asian country shaped like an S" },
    ],
    hard: [
      { word: "KYRGYZSTAN",       hint: "Central Asian country dominated by the Tian Shan mountains" },
      { word: "LIECHTENSTEIN",    hint: "Tiny double-landlocked country between Switzerland and Austria" },
      { word: "MOZAMBIQUE",       hint: "East African country whose flag features an AK-47" },
      { word: "DJIBOUTI",         hint: "Small East African nation on the Horn of Africa" },
      { word: "VANUATU",          hint: "Pacific island nation with over 100 indigenous languages" },
      { word: "ESWATINI",         hint: "Small African monarchy formerly known as Swaziland" },
      { word: "TIMOR-LESTE",      hint: "One of the world's youngest nations in Southeast Asia" },
      { word: "NAURU",            hint: "World's smallest island nation in the Pacific" },
      { word: "COMOROS",          hint: "African island nation off the east coast near Madagascar" },
      { word: "TURKMENISTAN",     hint: "Central Asian country with an eternal gas crater called the Door to Hell" },
    ],
  },

  // ── COMMON GAMES ─────────────────────────────────────────────────────────────
  "common games": {
    easy: [
      { word: "CHESS",       hint: "Strategy board game with kings and queens" },
      { word: "LUDO",        hint: "Board game with coloured tokens and dice" },
      { word: "CARROM",      hint: "Board game where you flick discs into pockets" },
      { word: "TAG",         hint: "Running game where one person chases others" },
      { word: "CHECKERS",    hint: "Board game of diagonal jumps on black squares" },
      { word: "JENGA",       hint: "Pull wooden blocks without toppling the tower" },
      { word: "UNO",         hint: "Card game where you yell the name when you have one card left" },
      { word: "SCRABBLE",    hint: "Tile-laying word game scored by letter values" },
      { word: "MINECRAFT",   hint: "Block-building survival game" },
      { word: "HIDE AND SEEK", hint: "One person counts while others hide" },
    ],
    medium: [
      { word: "AMONG US",      hint: "Space crewmate game with imposters" },
      { word: "FORTNITE",      hint: "Battle royale game with building mechanics" },
      { word: "VALORANT",      hint: "Tactical shooter with ability-based agents" },
      { word: "POKEMON GO",    hint: "Augmented reality game to catch creatures outside" },
      { word: "DUNGEONS AND DRAGONS", hint: "Tabletop RPG with dice and dungeon masters" },
      { word: "BATTLESHIP",    hint: "Guessing game where you find and sink enemy ships" },
      { word: "CONNECT FOUR",  hint: "Drop discs to get four in a row" },
      { word: "TABOO",         hint: "Describe words without using the forbidden ones" },
      { word: "CHARADES",      hint: "Act out a word or phrase without speaking" },
      { word: "MONOPOLY",      hint: "Board game of property buying and bankruptcy" },
    ],
    hard: [
      { word: "SLAY THE SPIRE",    hint: "Roguelike card-building dungeon game" },
      { word: "HOLLOW KNIGHT",     hint: "Dark insect metroidvania game underground" },
      { word: "DISCO ELYSIUM",     hint: "RPG where you play an amnesiac detective" },
      { word: "OUTER WILDS",       hint: "Space exploration game in an infinite time loop" },
      { word: "RETURN OF OBRA DINN",hint: "Puzzle game where you deduce deaths on a ghost ship" },
      { word: "BALDURS GATE THREE", hint: "Epic D&D-based RPG with branching storylines" },
      { word: "KATAMARI DAMACY",    hint: "Roll a sticky ball to rebuild the stars" },
      { word: "FIRE EMBLEM",        hint: "Nintendo tactical RPG series with permadeath" },
      { word: "ELDEN RING",         hint: "Open-world FromSoftware RPG with a shattered ring" },
      { word: "PATHFINDER",         hint: "Tabletop RPG descended from D&D 3.5 rules" },
    ],
  },

};

// ── TOPIC LIST ────────────────────────────────────────────────────────────────
const TOPICS = Object.keys(WORD_BANK);

// ── PICKER ────────────────────────────────────────────────────────────────────
// Returns a random { word, hint, topic } from the given difficulty
function pickWord(difficulty) {
  const level = (difficulty || "easy").toLowerCase();
  const topic = TOPICS[Math.floor(Math.random() * TOPICS.length)];
  const pool  = WORD_BANK[topic][level] || WORD_BANK[topic]["easy"];
  const pick  = pool[Math.floor(Math.random() * pool.length)];
  return { word: pick.word.toUpperCase(), hint: pick.hint, topic };
}